blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('api/', include('posts.api.urls'))
]

posts/api/urls.py
from django.urls import path

from posts.api.views import PostList, PostDetail, CommentByPostList

urlpatterns = [
    path('posts/', PostList.as_view()),
    path('posts/<int:pk>/', PostDetail.as_view()),
    path('posts/<int:pk>/comments/', CommentByPostList.as_view())
]

posts/urls.py
from django.urls import path

from posts import views
from posts.views import BlogListView, BlogDetailView

app_name = 'posts'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('<slug>', BlogDetailView.as_view(), name="detail"),
    path('<slug>/comment', views.comment, name="comment"),
    path('topic/<slug:slug>/', views.tagged, name='tagged')
]

# legacy URL patterns
# path('post/new', BlogCreateView.as_view(), name='new'),
# path('<slug>/update', BlogUpdateView.as_view(), name='update'),
# path('<slug>/delete', BlogDeleteView.as_view(), name='delete'),

posts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from taggit.managers import TaggableManager

# constant arguments for choices
DRAFT = 'draft'
PUBLISHED = 'published'
CHOICES = (
    (DRAFT, 'Draft'),
    (PUBLISHED, 'Published')
)


# menager that filters only published posts
# https://docs.djangoproject.com/en/2.2/topics/db/managers/#modifying-a-manager-s-initial-queryset
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=PUBLISHED)


class Post(models.Model):
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # !add related_name later!
    text = models.TextField()
    category = models.TextField(max_length=100)

    slug = models.SlugField(max_length=250,
                            unique_for_date='publish_date')  # converts the obtained data (eg. title) into URL with hyphens instead of spaces
    publish_date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=20, choices=CHOICES, default=PUBLISHED)

    # managers
    objects = models.Manager()  # default manager for all posts
    published = PublishedManager()  # custom manager only for published posts

    tags = TaggableManager()  # taggit manager

    def __str__(self):
        return '{}'.format(self.title)

    class Meta:  # default ordering of the posts according to the publish date
        ordering = ('-publish_date',)

    def get_absolute_url(self):  # redirects to the url with edited slug
        return reverse('posts:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):  # update slug when post is edited
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'Comment added to {self.post} by {self.author} on {self.publish_date}'

posts/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text',)

posts/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import generics

from posts.api.serializers import PostSerializer, PostListSerializer, CommentSerializer
from posts.models import Post, Comment


class PostList(generics.ListAPIView):
    queryset = Post.published.all()
    serializer_class = PostListSerializer


class PostDetail(generics.RetrieveAPIView):
    queryset = Post.published.all()
    serializer_class = PostSerializer


class CommentByPostList(generics.ListCreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

    def get_queryset(self):
        return Comment.objects.filter(post=self.kwargs['pk'])

posts/views.py
# Create your views here.
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, DetailView
from taggit.models import Tag

from posts.forms import CommentForm
from posts.models import Post


# class based views
class BlogListView(ListView):
    queryset = Post.published.all()  # modifies the displayed posts to only those with status = published
    model = Post
    template_name = 'posts/home.html'


class BlogDetailView(DetailView):
    queryset = Post.published.all()
    model = Post
    template_name = 'posts/detail.html'


# Function based views
def comment(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('posts:detail', slug=post.slug)
    else:
        form = CommentForm()
    return render(request, 'posts/comment.html', {'form': form})


def tagged(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    posts = Post.objects.filter(tags__in=[tag])

    context = {
        'tag': tag,
        'posts': posts,
    }
    return render(request, 'posts/tag_list.html', context)

# legacy views
# class BlogCreateView(CreateView):
#     model = Post
#     template_name = 'posts/new_legacy.html'
#     fields = ['title', 'author', 'text', 'tags']
#     success_url = reverse_lazy('posts:home')
#
#
# class BlogUpdateView(UpdateView):
#     model = Post
#     template_name = 'posts/update_legacy.html'
#     fields = ['title', 'text']
#
#
# class BlogDeleteView(DeleteView):
#     model = Post
#     template_name = 'posts/delete_legacy.html'
#     success_url = reverse_lazy('posts:home')

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<form method="POST" class="post-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-info">Send</button>
</form>
{% endblock %}

posts/templates/posts/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>COFFEE BLOG</title>
</head>


<body>
    <h1>Delete post</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <input type="submit" value="Confirm"/>
    </form>
</body>
</html>

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="blog-post">
    <h2 class="blog-post-title">{{ post.title}}</h2>
    <p class="tags">
        Tags: {% for tag in post.tags.all %}
        <a href="{% url 'posts:tagged' tag.slug %}" class="text-info">#{{ tag.name }}</a>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <p class="blog-post-meta">{{ post.publish_date }} by <a>{{ post.author }}</a></p>

    <p>{{ post.text|linebreaks }}</p>
    <a href="{% url 'posts:home' %}">
        <button type="button" class="btn btn-info ">Go back</button>
    </a>
    <br/>
    <br/>
    <br/>
</div><!-- /.blog-post -->

<hr/>

<h3>Comment section:</h3>
<a href="{% url 'posts:comment' post.slug %}" class="text-info font-weight-normal">Add comment</a>
<br/>
<br/>
{% for comment in post.comments.all %}
{% if comment.active %}
<div class="comment">
    <strong>{{ comment.author }}</strong>
    <br/>
    <a class="font-italic">{{ comment.publish_date }}</a>
    <br/>
    {{ comment.text|linebreaks }}
</div>
{% endif %}
{% empty %}
<p>No comments here yet :(</p>
{% endfor %}

{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %}
{% block content%}
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div>
        <h1 class="display-4 font-italic">{{ post_list.0.title }}</h1>
        <p class="lead my-3">{{ post_list.0.text|slice:":250" }}...</p>
        <p class="lead mb-0"><a href="{% url 'posts:detail' post_list.0.slug %}">
            <button type="button" class="btn btn-light">Continue reading...</button>
        </a></p>
    </div>
</div>
<div class="row mb-2">
    {% for post in post_list|slice:"1:3" %}
    <div class="col-md-6">
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <strong class="d-inline-block mb-2 text-info">{{ post.category }}</strong>
                <h3 class="mb-0">
                    <a class="text-dark">{{ post.title}}</a>
                </h3>
                <div class="mb-1 text-muted">{{ post.published_date }}</div>
                <p class="card-text mb-auto">{{ post.text|slice:":250" }}...</p>
                <br/>
                <a href="{% url 'posts:detail' post.slug %}">
                    <button type="button" class="btn btn-info ">Continue reading</button>
                </a>
            </div>

        </div>
    </div>
    {% endfor %}
</div>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            <h3 class="pb-3 mb-4 font-italic border-bottom">
                News
            </h3>
            {% for post in post_list|slice:"3:" %}
            <div class="blog-post">
                <h2 class="blog-post-title">{{ post.title}}</h2>
                <p>{{ post.publish_date }}</p>
                <p>{{ post.text|slice:":250" }}...</p>
                <a href="{% url 'posts:detail' post.slug %}">
                    <button type="button" class="btn btn-info ">Continue reading</button>
                </a>
                <br/>
                <br/>
                <br/>
            </div><!-- /.blog-post -->
            {% endfor %}
        </div><!-- /.row -->
        <aside class="col-md-4 blog-sidebar">
            <div class="p-3 mb-3 bg-light rounded">
                <h4 class="font-italic">About the author</h4>
                <p class="mb-0">Hi! I am Michał Kawa, a junior-level Python developer and I made this website as a part
                    of my ongoing self-study on Python. Let me know what you think!</p>
            </div>
            <div class="p-3">
                <h4 class="font-italic">Where you can find me</h4>
                <ol class="list-unstyled">
                    <li><a href="https://github.com/kawamichal">GitHub</a></li>
                    <li><a href="https://www.linkedin.com/in/kawa-michal/">LinkedIn</a></li>
                    <li><a href="http://michalkawa.azurewebsites.net/">Portfolio</a></li>
                    <li><a href="mailto:michal.kawa@hotmail.com">Mail</a></li>
                </ol>
            </div>
        </aside><!-- /.blog-sidebar -->
    </div>
</main><!-- /.container -->
{% endblock %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });



</script>
</body>
</html>

posts/templates/posts/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>COFFEE BLOG</title>
</head>


<body>
    <h1>New post</h1>
    <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
    </form>
</body>
</html>

posts/templates/posts/tag_list.html
{% extends 'base.html' %}
{%block content%}

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            {% if tag %}
            <h3 class="pb-3 mb-4 font-italic border-bottom">
                Posts tagged with #{{ tag.name }}:
            </h3>
            {% endif %}
            {% for post in posts %}
            <div class="blog-post">
                <h2 class="blog-post-title">{{ post.title}}</h2>
                <p class="tags">
                    Tags: {% for tag in post.tags.all %}
                    <a href="{% url 'posts:tagged' tag.slug %}" class="text-info">#{{ tag.name }}</a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <p class="blog-post-meta">{{ post.publish_date }} by <a>{{ post.author }}</a></p>

                <p>{{ post.text|slice:":250" }}...</p>
                <a href="{% url 'posts:detail' post.slug %}">
                    <button type="button" class="btn btn-info ">Continue reading</button>
                </a>
                <br/>
                <br/>
                <br/>
            </div><!-- /.blog-post -->
            {% endfor %}
        </div><!-- /.row -->
    </div>
</main><!-- /.container -->

{% endblock%}

posts/templates/posts/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>COFFEE BLOG</title>
</head>


<body>
    <h1>Update post</h1>
    <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update"/>
    </form>
</body>
</html>

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Coffee News</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/blog/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="blog.css" rel="stylesheet">
</head>

<body>
<div class="container">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-left">
            <div class="col-5 text-left">
                <a class="blog-header-logo text-dark" href="{% url 'posts:home' %}">
                    <h1 class="display-4 font-weight-bold">COFFEE NEWS</h1>
                </a>
            </div>
        </div>
    </header>

    <div class="nav-scroller py-1 mb-2">
        <hr/>
        <nav class="nav d-flex justify-content-between">

            {% load taggit_templatetags2_tags %}
            {% get_taglist as tags %}
            {% for tag in tags|slice:":12" %}
            <a class="p-2 text-muted" href="{% url 'posts:tagged' tag.slug %}"> #{{ tag }} </a>
            {% endfor %}
        </nav>
    </div>


    {% block content %}
    {% endblock%}



</div><!-- /.row -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });



</script>
</body>
</html>